import { IDoctor } from '@/models/doctors';

export const doctorsStub: IDoctor[] = [
  {
    id: 1,
    name: 'Dr. Emily Carter',
    appointmentDuration: 30,
    workingDays: [1, 2, 3, 4, 5],
    phone: '+1-555-1234',
    medicalFieldId: 1,
    isFemale: false,
  },
  {
    id: 2,
    name: 'Dr. Michael Johnson',
    appointmentDuration: 45,
    workingDays: [1, 3, 5, 6],
    phone: '+1-555-5678',
    medicalFieldId: 2,
    isFemale: false,
  },
  {
    id: 3,
    name: 'Dr. Sarah Lee',
    appointmentDuration: 20,
    workingDays: [0, 2, 3, 4, 5, 6],
    phone: '+1-555-9101',
    medicalFieldId: 3,
    isFemale: false,
  },
  {
    id: 4,
    name: 'Dr. Daniel Martinez',
    appointmentDuration: 25,
    workingDays: [1, 2, 3, 4, 5],
    phone: '+1-555-1122',
    medicalFieldId: 4,
    isFemale: false,
  },
  {
    id: 5,
    name: 'Dr. Olivia Brown',
    appointmentDuration: 30,
    workingDays: [1, 2, 3, 4, 5],
    phone: '+1-555-3344',
    medicalFieldId: 5,
    isFemale: false,
  },
  {
    id: 6,
    name: 'Dr. James Wilson',
    appointmentDuration: 40,
    workingDays: [1, 2, 4, 5],
    phone: '+1-555-5566',
    medicalFieldId: 6,
    isFemale: false,
  },
  {
    id: 7,
    name: 'Dr. Sophia Miller',
    appointmentDuration: 35,
    workingDays: [2, 3, 4, 5, 6],
    phone: '+1-555-7788',
    medicalFieldId: 7,
    isFemale: false,
  },
  {
    id: 8,
    name: 'Dr. William Anderson',
    appointmentDuration: 30,
    workingDays: [1, 2, 3, 4, 5],
    phone: '+1-555-9900',
    medicalFieldId: 8,
    isFemale: false,
  },
  {
    id: 9,
    name: 'Dr. Ava Hernandez',
    appointmentDuration: 45,
    workingDays: [1, 3, 5],
    phone: '+1-555-2233',
    medicalFieldId: 9,
    isFemale: false,
  },
  {
    id: 10,
    name: 'Dr. Benjamin Thompson',
    appointmentDuration: 25,
    workingDays: [0, 2, 3, 4, 5, 6],
    phone: '+1-555-4455',
    medicalFieldId: 10,
    isFemale: false,
  },
];
